services:
  event-service:
    build:
      context: ..
      dockerfile: ./event_service/Dockerfile
    container_name: event_service
    ports:
      - "8001:8000"
    env_file:
      - .env.event
    volumes:
      - ./alembic/versions:/app/alembic/versions
    depends_on:
      event-db:
        condition: service_healthy
    networks:
      - app_network
  
  event-db:
    image: postgres:15
    container_name: event-db
    env_file:
      - .env.db.event
    ports:
      - "5433:5432"
    volumes:
      - event_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  event_db_data:

networks:
  app_network:
    driver: bridge
